name: CMake

on:
  push:
    branches: [ builds_with_liblx ]
  pull_request:
    branches: [ builds_with_liblx ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Prepare Build Environment for libLX
      shell: bash
      run: |
        git clone https://github.com/sbmlteam/liblx.git
        mkdir ${{runner.workspace}}/liblx-build
    
    - name: Build libLX
      working-directory: ${{runner.workspace}}/liblx-build
      run: |
        cmake ${{github.workspace}}/liblx
        cmake --build .
        
    - name: Prepare Build Environment for testsbxml
      shell: bash
      run: |
        mkdir ${{runner.workspace}}/dependency
        mkdir ${{runner.workspace}}/dependency/include
        mkdir ${{runner.workspace}}/dependency/lib
        cp -r ${{github.workspace}}/liblx/src/liblx ${{runner.workspace}}/dependency/include
        cp ${{github.workspace}}/liblx-build/src/liblx.dylib ${{runner.workspace}}/dependency/lib
        
    - name: Configure CMake
      run: |
        cmake -B ${{runner.workspace}}/build \
          -DWITH_SWIG=False
          -DWITH_EXAMPLES=True

    - name: Build
      run: cmake --build ${{github.workspace}}/build
